// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: bounty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 悬赏相关请求/响应
type CreateBountyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Title             string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RewardAmount      int64                  `protobuf:"varint,3,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	EmployerAccountId int64                  `protobuf:"varint,4,opt,name=employer_account_id,json=employerAccountId,proto3" json:"employer_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateBountyRequest) Reset() {
	*x = CreateBountyRequest{}
	mi := &file_bounty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBountyRequest) ProtoMessage() {}

func (x *CreateBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBountyRequest.ProtoReflect.Descriptor instead.
func (*CreateBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBountyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBountyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBountyRequest) GetRewardAmount() int64 {
	if x != nil {
		return x.RewardAmount
	}
	return 0
}

func (x *CreateBountyRequest) GetEmployerAccountId() int64 {
	if x != nil {
		return x.EmployerAccountId
	}
	return 0
}

type CreateBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBountyResponse) Reset() {
	*x = CreateBountyResponse{}
	mi := &file_bounty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBountyResponse) ProtoMessage() {}

func (x *CreateBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBountyResponse.ProtoReflect.Descriptor instead.
func (*CreateBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

type ListBountiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PageId        int32                  `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBountiesRequest) Reset() {
	*x = ListBountiesRequest{}
	mi := &file_bounty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBountiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBountiesRequest) ProtoMessage() {}

func (x *ListBountiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBountiesRequest.ProtoReflect.Descriptor instead.
func (*ListBountiesRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{2}
}

func (x *ListBountiesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListBountiesRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListBountiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBountiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounties      []*Bounty              `protobuf:"bytes,1,rep,name=bounties,proto3" json:"bounties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBountiesResponse) Reset() {
	*x = ListBountiesResponse{}
	mi := &file_bounty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBountiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBountiesResponse) ProtoMessage() {}

func (x *ListBountiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBountiesResponse.ProtoReflect.Descriptor instead.
func (*ListBountiesResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{3}
}

func (x *ListBountiesResponse) GetBounties() []*Bounty {
	if x != nil {
		return x.Bounties
	}
	return nil
}

type GetBountyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBountyRequest) Reset() {
	*x = GetBountyRequest{}
	mi := &file_bounty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBountyRequest) ProtoMessage() {}

func (x *GetBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBountyRequest.ProtoReflect.Descriptor instead.
func (*GetBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{4}
}

func (x *GetBountyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	Applications  []*BountyApplication   `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBountyResponse) Reset() {
	*x = GetBountyResponse{}
	mi := &file_bounty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBountyResponse) ProtoMessage() {}

func (x *GetBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBountyResponse.ProtoReflect.Descriptor instead.
func (*GetBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{5}
}

func (x *GetBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

func (x *GetBountyResponse) GetApplications() []*BountyApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

var File_bounty_proto protoreflect.FileDescriptor

const file_bounty_proto_rawDesc = "" +
	"\n" +
	"\fbounty.proto\x12\x02pb\x1a\fcommon.proto\"\xa2\x01\n" +
	"\x13CreateBountyRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rreward_amount\x18\x03 \x01(\x03R\frewardAmount\x12.\n" +
	"\x13employer_account_id\x18\x04 \x01(\x03R\x11employerAccountId\":\n" +
	"\x14CreateBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"c\n" +
	"\x13ListBountiesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\">\n" +
	"\x14ListBountiesResponse\x12&\n" +
	"\bbounties\x18\x01 \x03(\v2\n" +
	".pb.BountyR\bbounties\"\"\n" +
	"\x10GetBountyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"r\n" +
	"\x11GetBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\x129\n" +
	"\fapplications\x18\x02 \x03(\v2\x15.pb.BountyApplicationR\fapplicationsB+Z)github.com/grayfalcon666/escrow-bounty/pbb\x06proto3"

var (
	file_bounty_proto_rawDescOnce sync.Once
	file_bounty_proto_rawDescData []byte
)

func file_bounty_proto_rawDescGZIP() []byte {
	file_bounty_proto_rawDescOnce.Do(func() {
		file_bounty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bounty_proto_rawDesc), len(file_bounty_proto_rawDesc)))
	})
	return file_bounty_proto_rawDescData
}

var file_bounty_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bounty_proto_goTypes = []any{
	(*CreateBountyRequest)(nil),  // 0: pb.CreateBountyRequest
	(*CreateBountyResponse)(nil), // 1: pb.CreateBountyResponse
	(*ListBountiesRequest)(nil),  // 2: pb.ListBountiesRequest
	(*ListBountiesResponse)(nil), // 3: pb.ListBountiesResponse
	(*GetBountyRequest)(nil),     // 4: pb.GetBountyRequest
	(*GetBountyResponse)(nil),    // 5: pb.GetBountyResponse
	(*Bounty)(nil),               // 6: pb.Bounty
	(*BountyApplication)(nil),    // 7: pb.BountyApplication
}
var file_bounty_proto_depIdxs = []int32{
	6, // 0: pb.CreateBountyResponse.bounty:type_name -> pb.Bounty
	6, // 1: pb.ListBountiesResponse.bounties:type_name -> pb.Bounty
	6, // 2: pb.GetBountyResponse.bounty:type_name -> pb.Bounty
	7, // 3: pb.GetBountyResponse.applications:type_name -> pb.BountyApplication
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bounty_proto_init() }
func file_bounty_proto_init() {
	if File_bounty_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bounty_proto_rawDesc), len(file_bounty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bounty_proto_goTypes,
		DependencyIndexes: file_bounty_proto_depIdxs,
		MessageInfos:      file_bounty_proto_msgTypes,
	}.Build()
	File_bounty_proto = out.File
	file_bounty_proto_goTypes = nil
	file_bounty_proto_depIdxs = nil
}
