// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EscrowBountyService_CreateBounty_FullMethodName   = "/pb.EscrowBountyService/CreateBounty"
	EscrowBountyService_ListBounties_FullMethodName   = "/pb.EscrowBountyService/ListBounties"
	EscrowBountyService_GetBounty_FullMethodName      = "/pb.EscrowBountyService/GetBounty"
	EscrowBountyService_AcceptBounty_FullMethodName   = "/pb.EscrowBountyService/AcceptBounty"
	EscrowBountyService_ConfirmHunter_FullMethodName  = "/pb.EscrowBountyService/ConfirmHunter"
	EscrowBountyService_CompleteBounty_FullMethodName = "/pb.EscrowBountyService/CompleteBounty"
	EscrowBountyService_CancelBounty_FullMethodName   = "/pb.EscrowBountyService/CancelBounty"
)

// EscrowBountyServiceClient is the client API for EscrowBountyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 统一服务接口
type EscrowBountyServiceClient interface {
	// 雇主发布悬赏
	CreateBounty(ctx context.Context, in *CreateBountyRequest, opts ...grpc.CallOption) (*CreateBountyResponse, error)
	// 获取悬赏大厅列表
	ListBounties(ctx context.Context, in *ListBountiesRequest, opts ...grpc.CallOption) (*ListBountiesResponse, error)
	// 获取单个悬赏详情
	GetBounty(ctx context.Context, in *GetBountyRequest, opts ...grpc.CallOption) (*GetBountyResponse, error)
	// 猎人申请接单
	AcceptBounty(ctx context.Context, in *AcceptBountyRequest, opts ...grpc.CallOption) (*AcceptBountyResponse, error)
	// 雇主选定猎人
	ConfirmHunter(ctx context.Context, in *ConfirmHunterRequest, opts ...grpc.CallOption) (*ConfirmHunterResponse, error)
	// 雇主确认完成并打款
	CompleteBounty(ctx context.Context, in *CompleteBountyRequest, opts ...grpc.CallOption) (*CompleteBountyResponse, error)
	// 雇主取消悬赏并退款
	CancelBounty(ctx context.Context, in *CancelBountyRequest, opts ...grpc.CallOption) (*CancelBountyResponse, error)
}

type escrowBountyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEscrowBountyServiceClient(cc grpc.ClientConnInterface) EscrowBountyServiceClient {
	return &escrowBountyServiceClient{cc}
}

func (c *escrowBountyServiceClient) CreateBounty(ctx context.Context, in *CreateBountyRequest, opts ...grpc.CallOption) (*CreateBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CreateBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ListBounties(ctx context.Context, in *ListBountiesRequest, opts ...grpc.CallOption) (*ListBountiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBountiesResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ListBounties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) GetBounty(ctx context.Context, in *GetBountyRequest, opts ...grpc.CallOption) (*GetBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_GetBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) AcceptBounty(ctx context.Context, in *AcceptBountyRequest, opts ...grpc.CallOption) (*AcceptBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_AcceptBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ConfirmHunter(ctx context.Context, in *ConfirmHunterRequest, opts ...grpc.CallOption) (*ConfirmHunterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmHunterResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ConfirmHunter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) CompleteBounty(ctx context.Context, in *CompleteBountyRequest, opts ...grpc.CallOption) (*CompleteBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CompleteBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) CancelBounty(ctx context.Context, in *CancelBountyRequest, opts ...grpc.CallOption) (*CancelBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CancelBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EscrowBountyServiceServer is the server API for EscrowBountyService service.
// All implementations must embed UnimplementedEscrowBountyServiceServer
// for forward compatibility.
//
// 统一服务接口
type EscrowBountyServiceServer interface {
	// 雇主发布悬赏
	CreateBounty(context.Context, *CreateBountyRequest) (*CreateBountyResponse, error)
	// 获取悬赏大厅列表
	ListBounties(context.Context, *ListBountiesRequest) (*ListBountiesResponse, error)
	// 获取单个悬赏详情
	GetBounty(context.Context, *GetBountyRequest) (*GetBountyResponse, error)
	// 猎人申请接单
	AcceptBounty(context.Context, *AcceptBountyRequest) (*AcceptBountyResponse, error)
	// 雇主选定猎人
	ConfirmHunter(context.Context, *ConfirmHunterRequest) (*ConfirmHunterResponse, error)
	// 雇主确认完成并打款
	CompleteBounty(context.Context, *CompleteBountyRequest) (*CompleteBountyResponse, error)
	// 雇主取消悬赏并退款
	CancelBounty(context.Context, *CancelBountyRequest) (*CancelBountyResponse, error)
	mustEmbedUnimplementedEscrowBountyServiceServer()
}

// UnimplementedEscrowBountyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEscrowBountyServiceServer struct{}

func (UnimplementedEscrowBountyServiceServer) CreateBounty(context.Context, *CreateBountyRequest) (*CreateBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ListBounties(context.Context, *ListBountiesRequest) (*ListBountiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBounties not implemented")
}
func (UnimplementedEscrowBountyServiceServer) GetBounty(context.Context, *GetBountyRequest) (*GetBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) AcceptBounty(context.Context, *AcceptBountyRequest) (*AcceptBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ConfirmHunter(context.Context, *ConfirmHunterRequest) (*ConfirmHunterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmHunter not implemented")
}
func (UnimplementedEscrowBountyServiceServer) CompleteBounty(context.Context, *CompleteBountyRequest) (*CompleteBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) CancelBounty(context.Context, *CancelBountyRequest) (*CancelBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) mustEmbedUnimplementedEscrowBountyServiceServer() {}
func (UnimplementedEscrowBountyServiceServer) testEmbeddedByValue()                             {}

// UnsafeEscrowBountyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EscrowBountyServiceServer will
// result in compilation errors.
type UnsafeEscrowBountyServiceServer interface {
	mustEmbedUnimplementedEscrowBountyServiceServer()
}

func RegisterEscrowBountyServiceServer(s grpc.ServiceRegistrar, srv EscrowBountyServiceServer) {
	// If the following call panics, it indicates UnimplementedEscrowBountyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EscrowBountyService_ServiceDesc, srv)
}

func _EscrowBountyService_CreateBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CreateBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CreateBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CreateBounty(ctx, req.(*CreateBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ListBounties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBountiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ListBounties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ListBounties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ListBounties(ctx, req.(*ListBountiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_GetBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).GetBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_GetBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).GetBounty(ctx, req.(*GetBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_AcceptBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).AcceptBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_AcceptBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).AcceptBounty(ctx, req.(*AcceptBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ConfirmHunter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmHunterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ConfirmHunter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ConfirmHunter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ConfirmHunter(ctx, req.(*ConfirmHunterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_CompleteBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CompleteBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CompleteBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CompleteBounty(ctx, req.(*CompleteBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_CancelBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CancelBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CancelBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CancelBounty(ctx, req.(*CancelBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EscrowBountyService_ServiceDesc is the grpc.ServiceDesc for EscrowBountyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EscrowBountyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EscrowBountyService",
	HandlerType: (*EscrowBountyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBounty",
			Handler:    _EscrowBountyService_CreateBounty_Handler,
		},
		{
			MethodName: "ListBounties",
			Handler:    _EscrowBountyService_ListBounties_Handler,
		},
		{
			MethodName: "GetBounty",
			Handler:    _EscrowBountyService_GetBounty_Handler,
		},
		{
			MethodName: "AcceptBounty",
			Handler:    _EscrowBountyService_AcceptBounty_Handler,
		},
		{
			MethodName: "ConfirmHunter",
			Handler:    _EscrowBountyService_ConfirmHunter_Handler,
		},
		{
			MethodName: "CompleteBounty",
			Handler:    _EscrowBountyService_CompleteBounty_Handler,
		},
		{
			MethodName: "CancelBounty",
			Handler:    _EscrowBountyService_CancelBounty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
