// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/grayfalcon666/escrow-bounty/db (interfaces: Store,BankClient)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination db/mock/store.go github.com/grayfalcon666/escrow-bounty/db Store,BankClient
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/grayfalcon666/escrow-bounty/db"
	models "github.com/grayfalcon666/escrow-bounty/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AcceptBounty mocks base method.
func (m *MockStore) AcceptBounty(ctx context.Context, bountyID, hunter_account_id int64, hunterUsername string) (*models.BountyApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptBounty", ctx, bountyID, hunter_account_id, hunterUsername)
	ret0, _ := ret[0].(*models.BountyApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptBounty indicates an expected call of AcceptBounty.
func (mr *MockStoreMockRecorder) AcceptBounty(ctx, bountyID, hunter_account_id, hunterUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptBounty", reflect.TypeOf((*MockStore)(nil).AcceptBounty), ctx, bountyID, hunter_account_id, hunterUsername)
}

// CancelBounty mocks base method.
func (m *MockStore) CancelBounty(ctx context.Context, bountyID int64, employerUsername string, bankClient db.BankClient, platformAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBounty", ctx, bountyID, employerUsername, bankClient, platformAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBounty indicates an expected call of CancelBounty.
func (mr *MockStoreMockRecorder) CancelBounty(ctx, bountyID, employerUsername, bankClient, platformAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBounty", reflect.TypeOf((*MockStore)(nil).CancelBounty), ctx, bountyID, employerUsername, bankClient, platformAccountID)
}

// CompleteBounty mocks base method.
func (m *MockStore) CompleteBounty(ctx context.Context, bountyID int64, employerUsername string, bankClient db.BankClient, platformAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteBounty", ctx, bountyID, employerUsername, bankClient, platformAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteBounty indicates an expected call of CompleteBounty.
func (mr *MockStoreMockRecorder) CompleteBounty(ctx, bountyID, employerUsername, bankClient, platformAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteBounty", reflect.TypeOf((*MockStore)(nil).CompleteBounty), ctx, bountyID, employerUsername, bankClient, platformAccountID)
}

// ConfirmHunter mocks base method.
func (m *MockStore) ConfirmHunter(ctx context.Context, bountyID, applicationID int64, employerUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmHunter", ctx, bountyID, applicationID, employerUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmHunter indicates an expected call of ConfirmHunter.
func (mr *MockStoreMockRecorder) ConfirmHunter(ctx, bountyID, applicationID, employerUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmHunter", reflect.TypeOf((*MockStore)(nil).ConfirmHunter), ctx, bountyID, applicationID, employerUsername)
}

// CreateApplication mocks base method.
func (m *MockStore) CreateApplication(ctx context.Context, app *models.BountyApplication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockStoreMockRecorder) CreateApplication(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockStore)(nil).CreateApplication), ctx, app)
}

// CreateBounty mocks base method.
func (m *MockStore) CreateBounty(ctx context.Context, bounty *models.Bounty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBounty", ctx, bounty)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBounty indicates an expected call of CreateBounty.
func (mr *MockStoreMockRecorder) CreateBounty(ctx, bounty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBounty", reflect.TypeOf((*MockStore)(nil).CreateBounty), ctx, bounty)
}

// GetBountyByID mocks base method.
func (m *MockStore) GetBountyByID(ctx context.Context, id int64) (*models.Bounty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBountyByID", ctx, id)
	ret0, _ := ret[0].(*models.Bounty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBountyByID indicates an expected call of GetBountyByID.
func (mr *MockStoreMockRecorder) GetBountyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBountyByID", reflect.TypeOf((*MockStore)(nil).GetBountyByID), ctx, id)
}

// ListBounties mocks base method.
func (m *MockStore) ListBounties(ctx context.Context, status models.BountyStatus, limit, offset int) ([]models.Bounty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBounties", ctx, status, limit, offset)
	ret0, _ := ret[0].([]models.Bounty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBounties indicates an expected call of ListBounties.
func (mr *MockStoreMockRecorder) ListBounties(ctx, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBounties", reflect.TypeOf((*MockStore)(nil).ListBounties), ctx, status, limit, offset)
}

// PublishBounty mocks base method.
func (m *MockStore) PublishBounty(ctx context.Context, bounty *models.Bounty, bankClient db.BankClient, employerAccountID, platformEscrowAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBounty", ctx, bounty, bankClient, employerAccountID, platformEscrowAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBounty indicates an expected call of PublishBounty.
func (mr *MockStoreMockRecorder) PublishBounty(ctx, bounty, bankClient, employerAccountID, platformEscrowAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBounty", reflect.TypeOf((*MockStore)(nil).PublishBounty), ctx, bounty, bankClient, employerAccountID, platformEscrowAccountID)
}

// UpdateApplicationStatus mocks base method.
func (m *MockStore) UpdateApplicationStatus(ctx context.Context, applicationID int64, status models.ApplicationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApplicationStatus", ctx, applicationID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateApplicationStatus indicates an expected call of UpdateApplicationStatus.
func (mr *MockStoreMockRecorder) UpdateApplicationStatus(ctx, applicationID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApplicationStatus", reflect.TypeOf((*MockStore)(nil).UpdateApplicationStatus), ctx, applicationID, status)
}

// UpdateBountyStatus mocks base method.
func (m *MockStore) UpdateBountyStatus(ctx context.Context, id int64, status models.BountyStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBountyStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBountyStatus indicates an expected call of UpdateBountyStatus.
func (mr *MockStoreMockRecorder) UpdateBountyStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBountyStatus", reflect.TypeOf((*MockStore)(nil).UpdateBountyStatus), ctx, id, status)
}

// MockBankClient is a mock of BankClient interface.
type MockBankClient struct {
	ctrl     *gomock.Controller
	recorder *MockBankClientMockRecorder
	isgomock struct{}
}

// MockBankClientMockRecorder is the mock recorder for MockBankClient.
type MockBankClientMockRecorder struct {
	mock *MockBankClient
}

// NewMockBankClient creates a new mock instance.
func NewMockBankClient(ctrl *gomock.Controller) *MockBankClient {
	mock := &MockBankClient{ctrl: ctrl}
	mock.recorder = &MockBankClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankClient) EXPECT() *MockBankClientMockRecorder {
	return m.recorder
}

// Transfer mocks base method.
func (m *MockBankClient) Transfer(ctx context.Context, fromAccount, toAccount, amount int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromAccount, toAccount, amount, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer.
func (mr *MockBankClientMockRecorder) Transfer(ctx, fromAccount, toAccount, amount, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockBankClient)(nil).Transfer), ctx, fromAccount, toAccount, amount, idempotencyKey)
}
