// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/grayfalcon666/escrow-bounty/db (interfaces: Store,BankClient)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/grayfalcon666/escrow-bounty/db"
	models "github.com/grayfalcon666/escrow-bounty/models"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AcceptBounty mocks base method.
func (m *MockStore) AcceptBounty(arg0 context.Context, arg1, arg2 int64, arg3 string) (*models.BountyApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptBounty", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.BountyApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptBounty indicates an expected call of AcceptBounty.
func (mr *MockStoreMockRecorder) AcceptBounty(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptBounty", reflect.TypeOf((*MockStore)(nil).AcceptBounty), arg0, arg1, arg2, arg3)
}

// CompleteBounty mocks base method.
func (m *MockStore) CompleteBounty(arg0 context.Context, arg1 int64, arg2 string, arg3 db.BankClient, arg4 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteBounty", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteBounty indicates an expected call of CompleteBounty.
func (mr *MockStoreMockRecorder) CompleteBounty(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteBounty", reflect.TypeOf((*MockStore)(nil).CompleteBounty), arg0, arg1, arg2, arg3, arg4)
}

// ConfirmHunter mocks base method.
func (m *MockStore) ConfirmHunter(arg0 context.Context, arg1, arg2 int64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmHunter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmHunter indicates an expected call of ConfirmHunter.
func (mr *MockStoreMockRecorder) ConfirmHunter(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmHunter", reflect.TypeOf((*MockStore)(nil).ConfirmHunter), arg0, arg1, arg2, arg3)
}

// CreateApplication mocks base method.
func (m *MockStore) CreateApplication(arg0 context.Context, arg1 *models.BountyApplication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockStoreMockRecorder) CreateApplication(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockStore)(nil).CreateApplication), arg0, arg1)
}

// CreateBounty mocks base method.
func (m *MockStore) CreateBounty(arg0 context.Context, arg1 *models.Bounty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBounty", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBounty indicates an expected call of CreateBounty.
func (mr *MockStoreMockRecorder) CreateBounty(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBounty", reflect.TypeOf((*MockStore)(nil).CreateBounty), arg0, arg1)
}

// GetBountyByID mocks base method.
func (m *MockStore) GetBountyByID(arg0 context.Context, arg1 int64) (*models.Bounty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBountyByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Bounty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBountyByID indicates an expected call of GetBountyByID.
func (mr *MockStoreMockRecorder) GetBountyByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBountyByID", reflect.TypeOf((*MockStore)(nil).GetBountyByID), arg0, arg1)
}

// ListBounties mocks base method.
func (m *MockStore) ListBounties(arg0 context.Context, arg1 models.BountyStatus, arg2, arg3 int) ([]models.Bounty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBounties", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Bounty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBounties indicates an expected call of ListBounties.
func (mr *MockStoreMockRecorder) ListBounties(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBounties", reflect.TypeOf((*MockStore)(nil).ListBounties), arg0, arg1, arg2, arg3)
}

// PublishBounty mocks base method.
func (m *MockStore) PublishBounty(arg0 context.Context, arg1 *models.Bounty, arg2 db.BankClient, arg3, arg4 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBounty", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBounty indicates an expected call of PublishBounty.
func (mr *MockStoreMockRecorder) PublishBounty(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBounty", reflect.TypeOf((*MockStore)(nil).PublishBounty), arg0, arg1, arg2, arg3, arg4)
}

// UpdateApplicationStatus mocks base method.
func (m *MockStore) UpdateApplicationStatus(arg0 context.Context, arg1 int64, arg2 models.ApplicationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApplicationStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateApplicationStatus indicates an expected call of UpdateApplicationStatus.
func (mr *MockStoreMockRecorder) UpdateApplicationStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApplicationStatus", reflect.TypeOf((*MockStore)(nil).UpdateApplicationStatus), arg0, arg1, arg2)
}

// UpdateBountyStatus mocks base method.
func (m *MockStore) UpdateBountyStatus(arg0 context.Context, arg1 int64, arg2 models.BountyStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBountyStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBountyStatus indicates an expected call of UpdateBountyStatus.
func (mr *MockStoreMockRecorder) UpdateBountyStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBountyStatus", reflect.TypeOf((*MockStore)(nil).UpdateBountyStatus), arg0, arg1, arg2)
}

// MockBankClient is a mock of BankClient interface.
type MockBankClient struct {
	ctrl     *gomock.Controller
	recorder *MockBankClientMockRecorder
}

// MockBankClientMockRecorder is the mock recorder for MockBankClient.
type MockBankClientMockRecorder struct {
	mock *MockBankClient
}

// NewMockBankClient creates a new mock instance.
func NewMockBankClient(ctrl *gomock.Controller) *MockBankClient {
	mock := &MockBankClient{ctrl: ctrl}
	mock.recorder = &MockBankClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankClient) EXPECT() *MockBankClientMockRecorder {
	return m.recorder
}

// Transfer mocks base method.
func (m *MockBankClient) Transfer(arg0 context.Context, arg1, arg2, arg3 int64, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer.
func (mr *MockBankClientMockRecorder) Transfer(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockBankClient)(nil).Transfer), arg0, arg1, arg2, arg3, arg4)
}
